FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl \
    && docker-php-ext-install pdo pdo_pgsql pgsql zip

RUN a2enmod rewrite

COPY ./custom.ini /usr/local/etc/php/conf.d/custom.ini
